### ISSUE TITLE
Delete all

### ISSUE THREAD

**Issue by c0nnector** [anupcowkur/Reservoir#14]
It would be nice to add an option to delete everything.

**Comment by matthew-reilly** [comment]
Wouldn't called init do it? Not sure.

**Comment by anupcowkur** [comment]
This has been left out intentionally. You're not supposed to worry about what's in the cache or how full it is. 

The design is such that you're only meant to put objects in to the cache. If there is less space, older objects will be thrown out to make space for the new one.

**Comment by c0nnector** [comment]
User case: You want to logout a user & delete everything associated with the current user session.

**Comment by anupcowkur** [comment]
@c0nnector that's a good use case. Let me validate it further.
