### ISSUE TITLE
Can' t set allowBackup to false

### ISSUE THREAD

**Issue by ciskeboekelo** [anupcowkur/Reservoir#15]
Due to this issue https://code.google.com/p/android/issues/detail?id=70073 and the fact the the reservoir library explicitly sets allowBackup to true, I can't set allowBackup to false.

Can allowBackup=true be removed from the manifest?

**Comment by anupcowkur** [comment]
will check this out.

**Comment by curioustechizen** [comment]
I've run into something similar before. The IDE templates for creating an Android library set the `allowBackup="true"` by default. For most libraries, it should be harmless to remove it (in fact, removing the entire `<application>`  element might also be appropriate).

**Comment by ciskeboekelo** [comment]
Great, thanks!
