### ISSUE TITLE
Should use getCacheDir() for storage

### ISSUE THREAD

**Issue by virl** [anupcowkur/Reservoir#16]
I think this library should use getCacheDir() for disk cache storage, because it stores temprorary data and not user documents.

http://developer.android.com/reference/android/content/Context.html#getCacheDir()

**Comment by anupcowkur** [comment]
the cache dir doesn't offer enough guarantees that the file will be there when the user asks for it.

**Comment by virl** [comment]
But that's exactly the purpose of the cache: to offer temporary storage that will be cleared up when system is out of resources.
If you're saving data not in caches dir, you're occupying app documents space with *temporary* data which user or system cannot clear without deleting useful user-generated documents of the app.
