### ISSUE TITLE
Multiple reservoirs with separate initialization

### ISSUE THREAD

**Issue by virl** [anupcowkur/Reservoir#17]
I think this library should not be initialized via static method, because it prevents creating multiple reservoirs and using it in different libraries.

**Comment by anupcowkur** [comment]
This is by intention. Reservoir is meant to be used as a singleton. Creating multiple instances will lead to confusion (Which instance did I put this object into?) and duplication (putting the same object into multiple instances) which makes things harder for developer.

The benefits in this case don't outweigh the costs.

**Comment by virl** [comment]
Singleton is very bad design pattern and commonly used only for system-wide services. But it is not right to use it for the cache, because user may need multiple caches in his app with different lifetime and size values.

And yes, cache instance must be aggregated inside the class that uses the cache, because it is implementation detail of that class which must not interfere with any other class that uses the cache. It is encapsulation.

That's why Android in-memory LruCache is not singleton.

**Comment by anupcowkur** [comment]
Sorry, but I disagree. Reservoir is better off as a singleton so as to provide a simple disk based cache. It might be the case for other libs where lifetime and size values are more relevant but not for a fire and forget minimalistic disk cache.
