### ISSUE TITLE
Use LruCache as front memory cache

### ISSUE THREAD

**Issue by virl** [anupcowkur/Reservoir#18]
I think this library should allow to use LruCache as front-end memory cache before DiskLruCache.

**Comment by anupcowkur** [comment]
I like the idea. Feel free to send a pull request.

**Comment by anupcowkur** [comment]
I like the idea. Feel free to send a PR.

**Comment by anupcowkur** [comment]
I like the idea. Feel free to send a PR.

**Comment by anupcowkur** [comment]
I like the idea. If you can send a PR along with speed tests that show significant speed improvements over the current implementation, I'm definitely willing to give it a go.
