### ISSUE TITLE
Error:Execution failed for task ':mobile:dexDebug'

### ISSUE THREAD

**Issue by Solitaryo** [anupcowkur/Reservoir#24]
When i try to run my project with your library i got this error every time:

Error:Execution failed for task ':mobile:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

This is my Gradle dependencies:

compile 'com.google.android.gms:play-services:7.5.0'
    compile 'com.google.code.findbugs:annotations:3.0.0'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.github.androidquery:androidquery:0.26.9'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'org.androidannotations:androidannotations-api:3.2'
    compile 'com.android.support:recyclerview-v7:21.0.0'
    compile "com.daimajia.swipelayout:library:1.2.0@aar"
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
//    compile 'com.anupcowkur:reservoir:2.0'
    // Design Support Library
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.android.support:design:22.2.0'

**Comment by anupcowkur** [comment]
Some jar is probably being imported multiple files. The solution is to find out which one and exclude it. This is not a library issue. See http://stackoverflow.com/questions/18021901/android-studio-gradle-build-fails-execution-failed-for-task-dexdebug
