### ISSUE TITLE
Comparison with Retrofit using Okhttp

### ISSUE THREAD

**Issue by Im-PJ** [anupcowkur/Reservoir#29]
I was using your library in a project but then I started using retrofit and recently came across this post http://blog.denevell.org/android-okhttp-retrofit-using-cache.html ,  which implies okhttp response cache can be used along with retrofit to cache network requests and use them offline. 
So can you highlight how reservoir is different than the above solution or can be it be used with retrofit in a better way. My use case is simple, I'm getting data from rest api using retrofit but the data changes rarely like once in a week. So which solution would work best for me?

**Comment by anupcowkur** [comment]
Hi. This isn't a library issue. It's a question that's more suited to StackOverflow perhaps so I'm closing it.

**Comment by Im-PJ** [comment]
Agreed. I posted here hoping to get better answers than SO since the library is relatively new, so to say. Anyways if you can share your views on the question, it would be helpful. Thanks.
