### ISSUE TITLE
Passing complex objects

### ISSUE THREAD

**Issue by ArthurSav** [anupcowkur/Reservoir#3]
Hi, i'm trying to use reservoir with an object extending another object but it gives me a 'NullpointerException' when i'm trying to get it from cache. So, is it a bug or it doesn't work with this kind of objects?

**Comment by robertoestivill** [comment]
What about overloading the `init` method and allow the Gson instance to be customizable?

This will allow developers to fully use Gson deserializers to get the most out of the cache.

```
init( Context context, long maxSize, Gson gson)

init( Context context, long maxSize ) {
  init( context, maxSize, new Gson());
}
```

Cheers
