### ISSUE TITLE
Delete operation seems not to work

### ISSUE THREAD

**Issue by AndroidGecko** [anupcowkur/Reservoir#30]
Reservoir.put("lol", "fsdfasdfa");
Reservoir.delete("lol");
Reservoir.contains("lol") returns true

Reservoir.put("lol", "fsdfasdfa");
Reservoir.clear()
Reservoir.contains("lol") returns false

**Comment by AndreiD** [comment]
it works man. you're just not doing it right...

**Comment by AndroidGecko** [comment]
Thanks @AndreiD care to explain?

**Comment by AndreiD** [comment]
I'll give you an example.

~~~~~
    User xUser = new User();
    xUser.name = "Andrei";

    try {
      Reservoir.put("myKey", xUser);
    } catch (Exception e) {
      e.printStackTrace();
    }

    try {
      Reservoir.delete("myKey");
    } catch (Exception e) {
      //failure
    }



    try {
      User myKey = Reservoir.get("myKey", User.class);
      Timber.d("HELLO FROM CACHE %s",myKey.name);
    } catch (Exception e) {
      e.printStackTrace();
    }
~~~~~
User is a simple class with a String name.

you'll get an exception....because the delete operation worked.
