### ISSUE TITLE
Support for expiration date

### ISSUE THREAD

**Issue by tobiasamon** [anupcowkur/Reservoir#31]
Hi,

this is already a nice implementation for a cache. But I have a feature request:
It would be nice to be able to specify an expiration time. When getting an item from the cache it would first check if the item exists and if it is expired. A Method should be passed to the get-request which will be executed to retrieve the new items which will be saved to cache after returning.
-> Observable<T> rxObject = cache.get(<KEY>, <FETCH_DATA>, <MAX_AGE>)
T: The type of the item
KEY: The key of the item
FETCH_DATA: A class that returns a list of T or a single T which is executed asynchronously

That's just a raw idea... but it would be very nice.

best regards
Tobias

**Comment by anupcowkur** [comment]
this has already been suggested before (#25). This library is not meant to handle expiry policies. That is up to the client to implement. All it is meant to do is to serialize and map objects to disk.
