### ISSUE TITLE
RxAndroid as a provided dependency

### ISSUE THREAD

**Issue by triveous** [anupcowkur/Reservoir#32]
Currently RxAndroid is added as a 'compile' dependency in the library, this can be an overhead (it adds around 3555 methods to the overall method count) to projects and upstream libraries which do not use RxAndroid. Can we offer the RxJava dependency as a 'provided' dependency to work around this? 

I'm also adding a Pull Request for reference, all the Espresso seem to pass.

**Comment by anupcowkur** [comment]
Sorry for the delay. Will merge this in soon.
