### ISSUE TITLE
Failed to invoke protected java.text.DateFormat() with no args

### ISSUE THREAD

**Issue by moderateepheezy** [anupcowkur/Reservoir#35]
I don't understand this error, the piece below logs the error

      Reservoir.getAsync("eventsData", resultType, new ReservoirGetCallback<List<EventsDataList>>(){
                 @Override
                 public void onSuccess(List<EventsDataList> events) {
                     //success
                     mAdapter.addAll(events);
                 }

                 @Override
                 public void onFailure(Exception e) {
                     //error
                     Log.d("ErrorLog", e.getMessage()); //This is where i get the error 
                 }
      });

**Comment by anupcowkur** [comment]
Whatever class you're putting into Reservoir needs a default no-arg constructor since it is required by GSON and Reservoir depends on it. Make sure that this is the case. It isn't a library bug so I'm closing it.
