### ISSUE TITLE
cannot access Observable class file for rx.Observable not found

### ISSUE THREAD

**Issue by ericn37** [anupcowkur/Reservoir#37]
this does not happen to `putAsync`. This only happens to `getAsync`.
My code:
```java
final Type resultType = new TypeToken<List<Category>>() {
        }.getType();
        Reservoir.getAsync("categories", resultType, new ReservoirGetCallback<List<Category>>() {
            @Override
            public void onSuccess(List<Category> categories) {
                //success
                Log.i(TAG, "onSuccess");
            }

            @Override
            public void onFailure(Exception e) {
                //error
                Log.e(TAG, "onFailure", e);
                fetchCatsFromRemote(object);
            }
        });
```

**Comment by anupcowkur** [comment]
Are you sure you've included RxJava correctly?

**Comment by ericn37** [comment]
It's not mentioned in your readme that I need to include RxJava to use `getAsync`. Also, `putAsync` is working fine for me so what is the root cause and solution for it?

**Comment by AndroidGecko** [comment]
@anupcowkur
Shouldn't this be optional?
I just updated from 2.1 and I'm getting same error
I don't use RxJava, I don't want to include it just to use this lib.

**Comment by anupcowkur** [comment]
It is optional. Unless you use the `getAsync` variant that returns observables, you shouldn't be having problems. Is this not the case? If it isn't, then let me know and I'll look into it.

**Comment by AndroidGecko** [comment]
just as in @ericn37 example. I just bumped it from 2.1 to 3.0.0 
never used RxJava in this project.
It fails during compilation on
```
Reservoir.getAsync(key, clazz, new ReservoirGetCallback() {
```
with `cannot access Observable class file for rx.Observable not found`

**Comment by anupcowkur** [comment]
Ok. Thanks for reporting. Will check this out.

**Comment by anupcowkur** [comment]
Fixed in `v3.1.0`. Please update your dependencies. Thanks for reporting this.

**Comment by rickytribbia** [comment]
Similar issue for me, but at init time. 

```
 Rejecting re-init on previously-failed class java.lang.Class<com.anupcowkur.reservoir.Reservoir$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lrx/Observable$OnSubscribe;
at void com.anupcowkur.reservoir.Reservoir.init(android.content.Context, long) (Reservoir.java:39)
```

It happens at: 

```
Reservoir.init(context, (5 * 1024 * 1024));
```

I add `reservoir` as dependency in app gradle file only with: 

```
compile 'com.anupcowkur:reservoir:3.1.0'
```

I don't want to use reactive into reservoir, because I already use `rxjava2` into the rest of the app and I don't want to have to add also `rxjava` as dependency.

**Comment by pooja-gaikwad15** [comment]
@rickytribbia any fixes?
