### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by MitchDroid** [anupcowkur/Reservoir#41]
Hi Guys, I getting this issue with the lib

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x81bb2c25 in tid 27598

do you know whats the cause?

Regards

**Comment by anupcowkur** [comment]
Gonna need more information than that. A full stacktrace would be a good start.

**Comment by anupcowkur** [comment]
Closed since there is no more info or progress on this.
