### ISSUE TITLE
Declares multiple JSON fields named id

### ISSUE THREAD

**Issue by erfannf** [anupcowkur/Reservoir#42]
The problem is kinda weird. When I try to store objects that have ID variables inside, I face this exception: 

java.lang.IllegalArgumentException: class xxxxx.Article declares multiple JSON fields named id .....

How to solve this problem?

**Comment by anupcowkur** [comment]
Can you post the class in question and all its superclasses (if any)?

**Comment by erfannf** [comment]
The class itself implements a private variable called id with getter and setter. I suspect this is the cause of problem. I will send the calss ASAP!

**Comment by anupcowkur** [comment]
Closed since there is no more info or progress on this. Can be re-opened again if problem persists.
