### ISSUE TITLE
null object reference!

### ISSUE THREAD

**Issue by khaledkhj** [anupcowkur/Reservoir#45]
Thanks for the great library, and here what I am getting

> Attempt to invoke virtual method 'java.lang.String com.anupcowkur.reservoir.SimpleDiskCache$StringEntry.getString()' on a null object reference

Any help please?

**Comment by anupcowkur** [comment]
What are you doing exactly? Code would help.

**Comment by khaledkhj** [comment]
Well, I just figured out why I am getting that,
I am doing kind of a complicated task, and I need it to have the key existed before doing any other tasks.
So, it is because of the key was not existed.

Thank you @anupcowkur

**Comment by anupcowkur** [comment]
Okay. Closing the issue.
