### ISSUE TITLE
putReservoir success, getReservoir failure

### ISSUE THREAD

**Issue by aat-antoine** [anupcowkur/Reservoir#5]
I have a strange behavior. I have called WS with okhttp + retrofit and I have retrieved POJO. Then I want save these objects with Reservoir. My method `putReservoir` goes in onSuccess but `getReservoir` goes in onFailure. In both side, I'm using the same object.

As a consequence, I have another question ==> Where are data on the phone ?

**Comment by xarlotie** [comment]
I'm also having that problem. I don't have to setup any path for cache right? So what's the issue?

**Comment by anupcowkur** [comment]
@xarlotie no, you don't have to set up a path. Can you make a sample that reproduces this?

**Comment by xarlotie** [comment]
I used it just as documented.

Reservoir.putAsync(key, apiResponse, new ReservoirPutCallback() {
                    @Override
                    public void onSuccess() {
                        Log.i("RestCache", "[PUT] Success: " + key);
                    }

                    @Override
                    public void onFailure(Exception e) {
                        Log.i("RestCache", "[PUT] Failed: " + key);
                    }
});

Reservoir.getAsync(this.key, ApiResponse.class, new ReservoirGetCallback<ApiResponse>() {
            @Override
            public void onSuccess(ApiResponse apiResponse) {
                Log.i("RestCache", "[GET] Success: " + key);
                try {
                    Log.i("RestCache", "Using cached data...");
                    callback.apiSuccess(tag, apiResponse, null, null);
                } catch (JSONException e) {
                    Log.i("RestCache", "Using cached data failed!");
                    e.printStackTrace();
                }
            }

            @Override
            public void onFailure(Exception e) {
            }
});

**Comment by anupcowkur** [comment]
Can you please give me the API response JSON that you receive and the ```ApiResponse``` class code as well?

**Comment by xarlotie** [comment]
I already simplified it. I tried String instead of my complicated ApiResponse class. Still doesnt work.

**Comment by anupcowkur** [comment]
The stack trace is fine but I need to see the exact server response and the model class if I am to fix this.

**Comment by xarlotie** [comment]
Here's a sample data:

    {
        "data":
        [
            {
                "movieid": 14920,
                "title": "Everly"
                "rating": "R-16",
                "poster": "http://ia.media-imdb.com/images/M/MV5BMjEyNTU4NTE5NV5BMl5BanBnXkFtZTgwNzY4NzIxNDE@._V1_SX214_AL_.jpg",
                "url": "http://www.imdb.com/title/tt1945084/",
                "release_date": "2015-02-11",
                "genre": "Action, Thriller",
                "critics_rating": 
                    {
                        "title": "‘Everly’ Lacks the Imagination to Make Up for its Minor Ambitions",
                        "articleid": 25056,
                        "rating": 1.5,
                        "rating_img": "http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/32/Actions-rating-icon.png"
                    }
            }
        ],
        "message": "",
        "status": true,
        "total": 22
    }

But i already tried to treat that as a String and not a custom class. It still does not work.

**Comment by matthew-reilly** [comment]
Seeing this as well.
