### ISSUE TITLE
rx.java seems not optionable - `Failed resolution of rx/Observable$onSubscribe` error

### ISSUE THREAD

**Issue by rickytribbia** [anupcowkur/Reservoir#51]
Hi, 
I added Reservoir to my project where I already use rxJava2. So I try to add Reservoir as dependency without rxJava reference. 

Into my gradle file I have only: 

```
compile 'com.anupcowkur:reservoir:3.1.0'
```

but I give this error: 

```
Rejecting re-init on previously-failed class java.lang.Class<com.anupcowkur.reservoir.Reservoir$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lrx/Observable$OnSubscribe;
```

I don't really want to add rxJava1 dependency to avoid a mess with rxJava2 imports.

Any suggestions?

**Comment by pooja-gaikwad15** [comment]
I am facing the same issue while executing Reservoir.init.. whereas havent implemented async anywhere in my project
