### ISSUE TITLE
Can we put multiple keys into cache?

### ISSUE THREAD

**Issue by androidCastle** [anupcowkur/Reservoir#52]
I want to cache the data with multiple keys and retrieve them. Like for example, first I want to save some data with key A and after that some data with key B and so on. And then retrieve that data based on the keys. Is that possible??

**Comment by anupcowkur** [comment]
one key will map to one object. You can't have two objects with the same key. You can put data A with key A and data B with Key B and retrieve them later.

**Comment by androidCastle** [comment]
I'm only able to retrieve the object for the last saved key and unable to retrieve the objects for previous keys.

**Comment by androidCastle** [comment]
It was a large data size related issue.
Closing it. Thanks.
