### ISSUE TITLE
Replace RxJava 1 with RxJava 2

### ISSUE THREAD

**Issue by anupcowkur** [anupcowkur/Reservoir#53]
RxJava 1 has reached end of life. Time to move to RxJava 2.

**Comment by subkanthi** [comment]
@anupcowkur I would like to volunteer for this work, if its OK, please let me know.

**Comment by anupcowkur** [comment]
Sure. Send a PR. I'll review it.

**Comment by SoniaW** [comment]
Has this been upgraded to RxJava 2?

**Comment by anupcowkur** [comment]
Hi. This library is deprecated and won't be maintained. Closing this issue.
