### ISSUE TITLE
What can be the causes for faliure for storing

### ISSUE THREAD

**Issue by rk8339811** [anupcowkur/Reservoir#54]
I am planning to use this library to store Hash. The size of the Hash may he up to 10,000 or even more. 

Can this library used to store Hash? 

Also what can be the possible causes for the failure of storing any object?

Any help would be really Grateful.

**Comment by anupcowkur** [comment]
> Can this library used to store Hash?

It can store any serializable object. Depending on what's in the object, size might be a constraint depending on what you have allocated to the lib.

> Also what can be the possible causes for the failure of storing any object?

Any normal reason IO would fail would apply here too I suppose.

**Comment by rk8339811** [comment]
@anupcowkur Thanks for the reply :)
